# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20181022_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
